; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = seeed_xiao_esp32s3_sense

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200

[env:seeed_xiao_esp32s3_sense]
board = seeed_xiao_esp32s3
board_build.psram = enabled
build_flags = 
    -DBOARD_HAS_PSRAM

; for wokwi simulation
;[env:esp32dev]
;board = esp32dev